# Composeファイルのバージョンを指定
version: '3.3'

volumes:
  tmp:
  public:
networks:
  web:
    driver: bridge

# 以下で各コンテナの設定を行う
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./infra/web/Dockerfile
    volumes:
      - ./infra/web/nginx.conf:/etc/nginx/nginx.conf
      - public:/app/public
      - tmp:/app/tmp
    ports:
      - "8081:80"
    depends_on:
      - app
    networks:
      - web

  app:
    container_name: app
    # サービスのベースイメージにDockerfileを指定
    build:
      context: .
      dockerfile: ./infra/app/Dockerfile
    stdin_open: true
    tty: true
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails server"
    # 環境変数
    environment:
      MYSQL_ROOT_PASSWORD: password
      BACK_DOMAIN: "localhost:3000"
    # 値を永続化
    volumes:
      - .:/app
      - public:/app/public
      - tmp:/app/tmp
    # dbサービスを先に起動するように定義
    depends_on:
      - db
    networks:
      - web

  db:
    container_name: db
    # dbサービスはDockerfileを持っていないので、ベースイメージを指定
    image: mysql:8.0
    # 環境変数
    environment:
      TZ: 'Asia/Tokyo'
      MYSQL_ROOT_PASSWORD: password
    # データベースの値を永続化
    volumes:
      - ./tmp/db:/var/lib/mysql
      - ./infra/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
    networks:
      - web
