# Composeファイルのバージョンを指定
version: '3.3'

# 以下で各コンテナの設定を行う
services:
  # 必要なDBコンテナを立ち上げている
  db:
    # dbサービスはDockerfileを持っていないので、ベースイメージを指定
    image: mysql:8.0
    # 環境変数
    environment:
      TZ: UTC
      MYSQL_ROOT_PASSWORD: password
    # データベースの値を永続化
    volumes:
      - ./tmp/db:/var/lib/mysql

  back:
    # サービスのベースイメージにDockerfileを指定
    build:
      context: .
      # Dockerfileに渡す値を指定
      args:
        WORKDIR: app
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    # 環境変数
    environment:
      MYSQL_ROOT_PASSWORD: password
      BACK_DOMAIN: "localhost:8080"
    # 値を永続化
    volumes:
      - ./app
    # dbサービスを先に起動するように定義
    depends_on:
      - db
    # 公開ポート番号を指定
    ports:
      - 3000:3000
