# fly.toml app configuration file generated for bosailv-back on 2024-06-03T11:18:48+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bosailv-back'
primary_region = 'nrt'

[build]
  dockerfile = './Dockerfile'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
