debug: true
env_name: '【開発環境】'
base_domain: 'bosailv-back.fly.dev'
base_image_url: 'https://bosailv-public-access-bucket.s3.ap-northeast-1.amazonaws.com'
redirect_whitelist: ['https://bosailv.vercel.app/*']
default_confirm_success_url: ''
default_password_reset_url: ''
default_unlock_success_url: ''
mailer_from:
  name: '%{app_name}'
  email: 'noreply@localhost'