debug: false
env_name: ''
base_domain: 'localhost.test'
base_image_url: 'http://localhost.test'
redirect_whitelist: ['http://front.localhost.test/*']
default_confirm_success_url: ''
default_password_reset_url: ''
default_unlock_success_url: ''
mailer_from:
  name: '%{app_name}'
  email: 'noreply@localhost.test'
