debug: false
env_name: ''
base_domain: 'localhost.test'
base_image_url: 'http://localhost.test'
redirect_whitelist: ['http://front.localhost.test/*']
default_confirm_success_url: ''
default_password_reset_url: ''
default_unlock_success_url: ''
mailer_from:
  name: '%{app_name}'
  email: 'noreply@localhost.test'

## お知らせ
# 一覧のデフォルト最大表示件数
default_infomations_limit: 4
test_infomations:
  all_forever_count: 1
  all_future_count: 1
  user_forever_count: 1
  user_future_count: 1

## 記事
# 一覧のデフォルト最大表示件数
default_articles_limit: 4
test_articles:
  genre_exist_count: 1
  favorite_exist_count: 1
